name: isa_kit
description: A powerful Flutter package for creating dynamic, user-configurable dashboards from a widget tree.
version: 0.0.1
homepage: https://github.com/isa-kit/isa-kit
repository: https://github.com/isa-kit/isa-kit

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

